import type { SettingsTab } from "@servicecoreui/ui/custom";

/* Genel Ayarlar — tüm sekme alanları (tek kaynak; SettingsForm bunu render eder).
 * Tab 1 (Genel) + Tab 2 (Genel Portal) ekranlardan birebir.
 * Tab 3-5 ekranları gelince doldurulacak. */
export const GENEL_AYARLAR_TABS: SettingsTab[] = [
  {
    key: "genel",
    label: "Genel Ayarlar",
    sections: [
      {
        key: "portal",
        layout: "grid",
        fields: [
          { key: "portal-adi", label: "Portal Adı", type: "text", defaultValue: "Servicecore Destek Merkezi" },
          { key: "portal-adresi", label: "Portal Adresi", type: "url", defaultValue: "servicedesk.company.com" },
          {
            key: "varsayilan-dil",
            label: "Varsayılan Dil",
            type: "select",
            defaultValue: "tr",
            options: [
              { value: "tr", label: "Türkçe" },
              { value: "en", label: "English" },
            ],
          },
        ],
      },
      {
        key: "bildirim",
        title: "Bildirimler",
        layout: "grid",
        fields: [
          { key: "eposta-bildirim", label: "E-Posta bildirimleri etkin", type: "switch", defaultChecked: true },
          { key: "eposta-issaati", label: "E-Posta bildirimlerini iş saatine göre gönder", type: "switch" },
        ],
      },
      {
        key: "gorseller",
        title: "Görseller",
        layout: "uploads",
        fields: [
          { key: "favicon", label: "Açık Favicon", type: "upload" },
          { key: "logo", label: "Açık Logo", type: "upload" },
          { key: "giris-logo", label: "Giriş Ekranı Logosu", type: "upload" },
          { key: "eposta-logo", label: "E-Posta Şablon Logosu", type: "upload" },
          { key: "arka-plan", label: "Giriş Ekranı Arka Plan Resmi", type: "upload" },
        ],
      },
    ],
  },
  {
    key: "portal-ayar",
    label: "Genel Portal Ayarları",
    sections: [
      {
        key: "renkler",
        title: "Renkler",
        layout: "grid",
        fields: [
          { key: "baslik-arkaplan", label: "Başlık Arka Plan Rengi", type: "color" },
          { key: "menu-arkaplan", label: "Menü Çubuğu Arka Plan Rengi", type: "color" },
          { key: "baslik-yazi", label: "Başlık Yazı Rengi", type: "color" },
          { key: "menu-yazi", label: "Menü Çubuğu Yazı Rengi", type: "color" },
          { key: "aktif-sekme-yazi", label: "Aktif Sekme Yazı Rengi", type: "color" },
        ],
      },
      {
        key: "ozel-kod",
        title: "Özel Kod",
        layout: "code",
        groups: [
          {
            key: "govde-oncesi",
            title: "Gövde Öncesi",
            fields: [
              { key: "govde-oncesi-css", label: "CSS", type: "code", language: "css", rows: 6 },
              { key: "govde-oncesi-js", label: "JavaScript", type: "code", language: "js", rows: 4 },
            ],
          },
          {
            key: "govde-sonrasi",
            title: "Gövde Sonrası",
            fields: [
              { key: "govde-sonrasi-css", label: "CSS", type: "code", language: "css", rows: 6 },
              { key: "govde-sonrasi-js", label: "JavaScript", type: "code", language: "js", rows: 4 },
            ],
          },
          {
            key: "ozel",
            title: "Özel",
            fields: [
              { key: "ozel-css", label: "CSS", type: "code", language: "css", rows: 6 },
              { key: "ozel-js", label: "JavaScript", type: "code", language: "js", rows: 4 },
            ],
          },
        ],
      },
    ],
  },
  {
    key: "kullanici-portal",
    label: "Kullanıcı Portal Ayarları",
    sections: [
      {
        key: "portal-ust",
        layout: "grid",
        fields: [
          { key: "kullanici-baslik", label: "Kullanıcı Başlık Yazısı", type: "text", defaultValue: "Customer Service & Support Center", full: true },
          { key: "musteri-arkaplan", label: "Müşteri Arka Plan Resmi", type: "upload" },
          { key: "kullanici-baslik-renk", label: "Kullanıcı Başlık Yazısı Rengi", type: "color" },
        ],
      },
      {
        key: "modul-yetkileri",
        title: "Kullanıcı Portalı — Modül Yetkileri",
        layout: "checkboxes",
        options: [
          { key: "modul-katalog", label: "Katalog", defaultChecked: true },
          { key: "modul-projeler", label: "Projeler", defaultChecked: true },
          { key: "modul-cozumler", label: "Çözümler", defaultChecked: true },
          { key: "modul-varliklar", label: "Varlıklar", defaultChecked: true },
          { key: "modul-servisler", label: "Servisler", defaultChecked: true },
          { key: "modul-cagrilar", label: "Çağrılar", defaultChecked: true },
          { key: "modul-olaylar", label: "Olaylar", defaultChecked: true },
          { key: "modul-iyilestirmeler", label: "İyileştirmeler", defaultChecked: true },
          { key: "modul-duyurular", label: "Duyurular", defaultChecked: true },
          { key: "modul-soru-sor", label: "Soru Sor", defaultChecked: true },
        ],
      },
      {
        key: "ana-ekran",
        title: "Kullanıcı Ana Ekranı",
        layout: "checkboxes",
        options: [
          { key: "ana-yeni-olay", label: "Yeni Olay", defaultChecked: true },
          { key: "ana-yeni-istek", label: "Yeni İstek", defaultChecked: true },
          { key: "ana-yeni-si", label: "Yeni SI", defaultChecked: true },
          { key: "ana-bilgi-bankasi", label: "Bilgi Bankası", defaultChecked: true },
          { key: "ana-bekleyen-goster", label: "Açılışta Bekleyen Kayıtları da Göster", defaultChecked: true },
          { key: "ana-zimmet-gizle", label: "Varlık Gridindeki Zimmet Butonlarını Gizle" },
        ],
      },
      {
        key: "olay-guncellenebilir",
        title: "Olay Güncellenebilir Alanlar",
        layout: "checkboxes",
        options: [
          { key: "olay-tekrar-ac", label: "Kapanan Olayı Tekrar Açabilir", defaultChecked: true },
          { key: "olay-kapatabilir", label: "Olay Kaydını Kapatabilir", defaultChecked: true },
        ],
      },
      {
        key: "yeni-olay-alanlari",
        title: "Yeni Olay Alanları Yetkileri",
        layout: "checkboxes",
        options: [
          { key: "yolay-konu", label: "Konu", defaultChecked: true },
          { key: "yolay-aciklama", label: "Açıklama", defaultChecked: true },
          { key: "yolay-baskasi-icin", label: "Başkası İçin Olay", defaultChecked: true },
          { key: "yolay-bildirilecek-kisi", label: "Bildirilecek Diğer Kişi", defaultChecked: true },
          { key: "yolay-aciliyet", label: "Aciliyet", defaultChecked: true },
          { key: "yolay-etki", label: "Etki", defaultChecked: true },
          { key: "yolay-kategori", label: "Kategori", defaultChecked: true },
          { key: "yolay-dosya-ekleme", label: "Dosya Ekleme", defaultChecked: true },
          { key: "yolay-dosya-goruntuleme", label: "Dosya Görüntüleme", defaultChecked: true },
          { key: "yolay-sirketler", label: "Şirketler" },
          { key: "yolay-olay-sablonu", label: "Olay Şablonu", defaultChecked: true },
          { key: "yolay-sablon-zorunlu", label: "Olay Şablonu Zorunlu" },
          { key: "yolay-konum", label: "Konum", defaultChecked: true },
          { key: "yolay-ust-kategori", label: "Üst kategori seçilebilir", defaultChecked: true },
          { key: "yolay-iliskili-gorev-kapat", label: "Kayıt Kapatılınca İlişkili Görevler Kapatılsın" },
          { key: "yolay-oncelik", label: "Öncelik", defaultChecked: true },
        ],
      },
      {
        key: "yeni-istek-alanlari",
        title: "Yeni İstek Alanları Yetkileri",
        layout: "checkboxes",
        options: [
          { key: "yistek-aciklama", label: "Açıklama", defaultChecked: true },
          { key: "yistek-konu", label: "Konu", defaultChecked: true },
          { key: "yistek-baskasi-icin", label: "Başkası İçin İstek", defaultChecked: true },
          { key: "yistek-bildirilecek-kisi", label: "Bildirilecek Diğer Kişi", defaultChecked: true },
          { key: "yistek-paylasilacak", label: "Paylaşılacak Kullanıcılar", defaultChecked: true },
          { key: "yistek-sirketler", label: "Şirketler" },
          { key: "yistek-konu-duzenleme", label: "Konu Düzenleme", defaultChecked: true },
          { key: "yistek-aciklama-duzenleme", label: "Açıklama Düzenleme", defaultChecked: true },
          { key: "yistek-yeniden-ac-kapat", label: "Yeniden Aç - Kapat Butonu", defaultChecked: true },
          { key: "yistek-konum", label: "Konum", defaultChecked: true },
          { key: "yistek-aciliyet", label: "Aciliyet", defaultChecked: true },
          { key: "yistek-etki", label: "Etki", defaultChecked: true },
          { key: "yistek-varlik", label: "Varlık" },
          { key: "yistek-lokasyon-zorunlu", label: "Lokasyon Zorunlu" },
          { key: "yistek-dosya-ekle", label: "Dosya Ekle", defaultChecked: true },
          { key: "yistek-iliskili-gorev-kapat", label: "Kayıt Kapatılınca İlişkili Görevler Kapatılsın" },
          { key: "yistek-diger-alanlar", label: "Diğer Alanlar" },
        ],
      },
      {
        key: "yeni-iyilestirme-alanlari",
        title: "Yeni İyileştirme Alanları Yetkileri",
        layout: "checkboxes",
        options: [
          { key: "yiyi-konu", label: "Konu", defaultChecked: true },
          { key: "yiyi-aciklama", label: "Açıklama", defaultChecked: true },
          { key: "yiyi-baskasi-icin", label: "Başkası İçin İyileştirme", defaultChecked: true },
          { key: "yiyi-paylasilacak", label: "Paylaşılacak Kullanıcılar" },
          { key: "yiyi-aciliyet", label: "Aciliyet", defaultChecked: true },
          { key: "yiyi-etki", label: "Etki" },
          { key: "yiyi-kategori", label: "Kategori", defaultChecked: true },
          { key: "yiyi-bolum", label: "Bölüm", defaultChecked: true },
          { key: "yiyi-dosya-ekle", label: "Dosya Ekle", defaultChecked: true },
          { key: "yiyi-sirketler", label: "Şirketler", defaultChecked: true },
          { key: "yiyi-konum", label: "Konum", defaultChecked: true },
          { key: "yiyi-ozel-ek-alanlar", label: "Özel Ek Alanlar" },
          { key: "yiyi-iyilestirme-sablonu", label: "İyileştirme Şablonu" },
          { key: "yiyi-ust-kategori", label: "Üst kategori seçilebilir" },
        ],
      },
      {
        key: "profil-alanlari",
        title: "Son Kullanıcı Profil Alanları Yetkileri",
        layout: "checkboxes",
        options: [
          { key: "profil-2fa", label: "İki Faktörlü Kimlik Doğrulaması", defaultChecked: true },
        ],
      },
    ],
  },
  {
    key: "uygulama",
    label: "Uygulama Ayarları",
    sections: [
      {
        key: "uyg-eposta",
        title: "E-posta Davranışları",
        layout: "stack",
        fields: [
          { key: "uyg-kullanici-aktif-eposta", label: "Kullanıcı etkinleştirildiğinde e-posta gönder", type: "switch", defaultChecked: true },
          { key: "uyg-hosgeldin-eposta", label: "Kullanıcı Oluşturulduğunda Hoş Geldiniz E-Postası Gönder", type: "switch", defaultChecked: true },
          { key: "uyg-eposta-tarih-goster", label: "Epostanın gönderildiği tarihi de göster", type: "switch", defaultChecked: true },
          { key: "uyg-pasif-kullanici-eposta", label: "Pasif Kullanıcılara E-Posta Gönderilsin mi?", type: "switch", defaultChecked: true },
          { key: "uyg-anket-eposta-domain", label: "Anket tamamlama aşamasında girilen eposta adresi tanımlı bir domain olmalımıdır?", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-cozum-kapatma",
        title: "Çözüm ve Kapatma",
        layout: "stack",
        fields: [
          {
            key: "uyg-varsayilan-cozum-tipi",
            label: "Varsayılan Çözüm Tipi",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            key: "uyg-olay-cozuldu-durum",
            label: "Olay için çözüldü olarak kabul edilecek durum",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
            help: "E-posta bildirimlerinde çözüm şablonunu kontrol ediniz",
          },
          {
            key: "uyg-istek-cozuldu-durum",
            label: "İstek için çözüldü olarak kabul edilecek durum",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
            help: "E-posta bildirimlerinde çözüm şablonunu kontrol ediniz",
          },
          { key: "uyg-sr-cozuldu-kapatma-kurali-yoksay", label: "Çözüldü Durumuna Geçince Kapatma Kurallarını Yoksay", type: "switch", defaultChecked: true },
          { key: "uyg-kapali-ticket-email-kontrol", label: "Kapalı Ticket Email Davranış Kontrolü", type: "switch", defaultChecked: true },
          {
            dependsOn: "uyg-kapali-ticket-email-kontrol",
            key: "uyg-kapali-ticket-yeniden-ac",
            label: "Kapalı Ticket Email Davranışı N kadar dakika geçmişse",
            type: "composite",
            controls: [
              { key: "dakika", control: "number", min: 0 },
              { key: "yeniden-ac-durum", control: "select", placeholder: "Kapalı ticket açılırken atanacak durum", searchable: true, options: [] },
            ],
          },
          {
            key: "uyg-otomatik-kapatma",
            label: "Otomatik Kapatma Süresi (Dakika)",
            type: "composite",
            controls: [
              { key: "sure", control: "number", defaultValue: 2880, min: 0 },
              { key: "gerekce", control: "select", placeholder: "Varsayılan kapatma gerekçesi seçiniz.", searchable: true, options: [] },
              { key: "aciklama", control: "text", placeholder: "Çözüm açıklaması" },
            ],
          },
          {
            key: "uyg-istek-otomatik-kapatma",
            label: "İstek Otomatik Kapatma Süresi (Dakika)",
            type: "composite",
            controls: [
              { key: "sure", control: "number", defaultValue: 0, min: 0 },
              { key: "gerekce", control: "select", placeholder: "Varsayılan kapatma gerekçesi seçiniz.", searchable: true, options: [] },
              { key: "gerekce-yazi", control: "text", placeholder: "Varsayılan kapatma gerekçesi yazınız." },
            ],
          },
          { key: "uyg-bildirimsiz-kapatma", label: "Bildirimsiz Kapatma Özelliği", type: "switch", defaultChecked: true },
          { key: "uyg-sr-kapatma-gerekce-zorunlu", label: "SR Kapatma Gerekçesi Zorunlumu", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-buton-gorunurluk",
        title: "Buton Görünürlüğü",
        layout: "stack",
        fields: [
          { key: "uyg-coz-gorunur", label: "Çöz Butonunu Görünür Yap", type: "switch", defaultChecked: true },
          { key: "uyg-yeni-olay-kullanici-ekle", label: "Yeni Olay Sayfasından Kullanıcı Ekle Butonu", type: "switch", defaultChecked: true },
          { key: "uyg-kapat-gizli", label: "Kapat Butonunu Gizli Yap", type: "switch", defaultChecked: true },
          { key: "uyg-bana-ata-gizli", label: "Bana Ata Butonunu Gizli Yap", type: "switch", defaultChecked: true },
          { key: "uyg-reddet-gizli", label: "Reddet Butonunu Gizli Yap", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-zaman",
        title: "Zaman Takibi",
        layout: "stack",
        fields: [
          { key: "uyg-otomatik-zaman-kapat", label: "Otomatik Zaman Kaydediciyi Devre Dışı Bırak", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-arama",
        title: "Arama",
        layout: "stack",
        fields: [
          { key: "uyg-aktif-olmayan-kullanici-ara", label: "Aktif Olmayan Kullanıcılarıda Ara", type: "switch", defaultChecked: true },
          { key: "uyg-aktif-olmayan-teknisyen-ara", label: "Aktif Olmayan Teknisyenleride Ara", type: "switch", defaultChecked: true },
          { key: "uyg-arama-motoru-cron", label: "Arama Motoru Güncelleme Aralığı (Cron)", type: "text", placeholder: "Örn: 0 */15 * * *" },
        ],
      },
      {
        key: "uyg-gorunum",
        title: "Görünüm ve Panel",
        layout: "stack",
        fields: [
          { key: "uyg-son-kullanici-bilgi", label: "Son kullanıcı panelinde kullanıcı bilgileri gösterilsin mi?", type: "switch", defaultChecked: true },
          { key: "uyg-alt-sirket-kontrol", label: "Alt Şirket Bilgisi Kontrol Alanı", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-guncellenen-olay-ust", label: "Güncellenen Olaylar Üst Sırada Görünsün mü?", type: "switch", defaultChecked: true },
          { key: "uyg-sirket-holding-modu", label: "Şirket Gösterimini Holding Modunda Yap", type: "switch", defaultChecked: true },
          { key: "uyg-onay-kodu-alani", label: "Kullanıcı Onay Kodu Alanı", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-kullanici-secme-ekstra", label: "Kullanıcı seçme listelerinde görünecek ekstra alan", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-teknisyen-secme-ekstra", label: "Teknisyen seçme listelerinde görünecek ekstra alan", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-ust-menu-bildirim-gizle", label: "Üst Menüdeki Bildirimleri Gizle", type: "switch", defaultChecked: true },
          { key: "uyg-modul-detay-lobby-kapat", label: "Kim görüntülüyor özelliği kapatılsın", type: "switch", defaultChecked: true },
          { key: "uyg-teknisyen-grup-alfabetik", label: "Teknisyen Gruplarını Alfabetik Olarak Sırala", type: "switch", defaultChecked: true },
          { key: "uyg-navigasyon-ozel-buton", label: "Navigasyon alanı özel buton ayarları", type: "textarea", rows: 4 },
        ],
      },
      {
        key: "uyg-sla",
        title: "SLA",
        layout: "stack",
        fields: [
          { key: "uyg-sla-sayilan-sure", label: "SLA varsayılan süre(dakika)", type: "number", defaultValue: 0, min: 0 },
          { key: "uyg-olay-sla-tekrar", label: "Olay Güncellendiğinde SLA Policy Tekrar Uygulansın", type: "switch", defaultChecked: true },
          { key: "uyg-sla-istek-modulu", label: "SLA Policy'leri İstek Modülüne de Uygula", type: "switch", defaultChecked: true },
          {
            dependsOn: "uyg-sla-istek-modulu",
            key: "uyg-istek-sla-tekrar",
            label: "İstek Güncellendiğinde SLA Policy Tekrar Uygulansın",
            type: "switch",
            defaultChecked: true,
          },
        ],
      },
      {
        key: "uyg-kayit",
        title: "Kayıt Davranışları",
        layout: "stack",
        fields: [
          {
            key: "uyg-olay-kimlik-baslama",
            label: "Olaylar İçin Kimlik Başlama Numarası",
            type: "number",
            defaultValue: 146,
            min: 0,
            help: "Değiştirmek için Kaydet butonunu kullanın.",
          },
          { key: "uyg-gorev-tamamlanma-100", label: "Görev Tamamlandığında Tamamlanma Yüzdesini 100 Olarak Güncelle", type: "switch", defaultChecked: true },
          { key: "uyg-istek-konu-otomatik-doldurma", label: "İstek kaydı açılırken konu otomatik doldurulmasın", type: "switch", defaultChecked: true },
          { key: "uyg-baskasi-istek-konu-degis", label: "Başkası Adına İstek Oluştururken Konu Değişsin mi?", type: "switch", defaultChecked: true },
          { key: "uyg-acilirken-sirket-ekle", label: "Olay, İstek veya İyileştirme Açılırken Şirket Seçilmemişse Kullanıcının Şirketi Eklensin mi?", type: "switch", defaultChecked: true },
          { key: "uyg-acilirken-konum-ekle", label: "Olay, İstek veya İyileştirme Açılırken Konum Seçilmemişse Kullanıcının Konumu Eklensin mi?", type: "switch", defaultChecked: true },
          { key: "uyg-kapatilmis-kayit-duzenle", label: "Kapatılmış Kaydı Düzenleyebilir", type: "switch", defaultChecked: true },
          { key: "uyg-zimmet-teslim-eden-kullanici", label: "Zimmet formunu alan kullanıcı, zimmeti veren (teslim eden) olarak alınsın mı?", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-istek-onay",
        title: "İstek Ayarları",
        layout: "stack",
        fields: [
          { key: "uyg-istek-paylasilan-bilgilendir", label: "Paylaşılan Kullanıcıları Bilgilendir", type: "switch", defaultChecked: true },
          { key: "uyg-istek-onay-bekleniyor", label: "İstek için onay bekleniyor olarak kabul edilecek durum", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-istek-onaylandi", label: "İstek için onaylandı olarak kabul edilecek durum", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-istek-reddedildi", label: "İstek için reddedildi olarak kabul edilecek durum", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          {
            key: "uyg-onay-bekleyen-aksiyon",
            label: "Onayda bekleyen kayıtların üzerinden x gün geçmiş ise otomatik olarak aksiyon al",
            type: "composite",
            controls: [
              { key: "aktif", control: "select", placeholder: "Onayda bekleyen kayıtların üzerinden", searchable: true, options: [] },
              { key: "gun", control: "number", defaultValue: 4, min: 0 },
              { key: "aksiyon", control: "select", placeholder: "gün kadar geçmiş ise otomatik olarak", searchable: true, options: [] },
            ],
          },
          {
            // koşullu: uyg-onay-bekleyen-aksiyon
            key: "uyg-onay-bekleyen-gerekce",
            label: "Geciken Kayıtların Onay Açıklaması",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            key: "uyg-istek-gorev-teknisyen-ata",
            label: "İstek modülü için göreve atanan teknisyeni ve teknisyen grubunu istek kaydına ata",
            type: "switch",
            defaultChecked: true,
            help: "Görev kaydındaki hem teknisyenin hem teknisyen grubunun istek kaydına atamasını yapar. Görev kaydının boş olması durumunda teknisyen istek kaydının grubuna üye bir teknisyen ise direkt atanır fakat farklı grupta ise istek kaydının grup bilgisi boşaltılır.",
          },
          { key: "uyg-istek-gorev-diger-kullanici-eslestir", label: "Diğer kullanıcı adına açılan kayıtlar için onun şirketini kullan", type: "switch", defaultChecked: true },
          { key: "uyg-istek-gecmis-sadelestir", label: "İstek geçmiş alanı sadeleştirilsin mi?", type: "switch", defaultChecked: true },
          { key: "uyg-istek-pano-kolon-sadelestir", label: "Panoda istek gridindeki kolonlar sadeleştirilsin mi?", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-ilk-mudahale",
        title: "İlk Müdahale Aksiyonu",
        layout: "stack",
        fields: [
          { key: "uyg-olay-ilk-mudahale", label: "Olay Modülü İçin İlk Müdahale Aksiyonu", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-istek-ilk-mudahale", label: "İstek Modülü İçin İlk Müdahale Aksiyonu", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
        ],
      },
      {
        key: "uyg-dosya",
        title: "Dosya Ayarları",
        layout: "stack",
        fields: [
          { key: "uyg-izin-dosya", label: "İzin Verilen Dosya Listesi", type: "tags", defaultValue: ["svg", "json", "png", "jpeg", "jpg", "txt", "pdf", "docx", "xsl"] },
          { key: "uyg-izin-resim", label: "İzin Verilen Resim Dosya Listesi", type: "tags", defaultValue: ["svg", "png", "jpeg", "jpg", "txt"] },
          { key: "uyg-dosya-imza-kontrol", label: "Dosya kontrolü yapılırken dosya imzasına bakılsın", type: "switch", defaultChecked: true },
          { key: "uyg-maks-dosya-boyut", label: "Maks. Dosya Büyüklüğü", type: "number", defaultValue: 10, min: 1 },
        ],
      },
      {
        key: "uyg-problem",
        title: "Problem",
        layout: "stack",
        fields: [
          { key: "uyg-problem-kapat-olaylar", label: "Problem kapatılırsa bağlantılı olayları kapat", type: "switch", defaultChecked: true },
          {
            dependsOn: "uyg-problem-kapat-olaylar",
            key: "uyg-problem-olay-kapatma-esgec",
            label: "Bağlantılı olayları kapatılırken kapatma kurallarını es geç",
            type: "switch",
            defaultChecked: true,
          },
          {
            dependsOn: "uyg-problem-kapat-olaylar",
            key: "uyg-problem-cozum-olaya-kopyala-oto",
            label: "Bu ayar etkinleştirildiğinde, bir problem kaydına girilen çözümler otomatik olarak ilgili olay kayıtlarına da kopyalanır. Böylece problem ile ilişkili tüm olaylarda aynı çözüm bilgisi görünür ve süreçler arasında tutarlılık sağlanır.",
            type: "switch",
            defaultChecked: true,
          },
          {
            dependsOn: "uyg-problem-kapat-olaylar",
            key: "uyg-problem-kapatinca-olay-durum",
            label: "Problemi Kapattığınızda Bağlantılı Olayların Durumunu Değiştirin",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            dependsOn: "uyg-problem-kapat-olaylar",
            key: "uyg-problem-kapatma-gerekce",
            label: "Kapatılacak bağlantılı olayların kapatma gerekçesi",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            dependsOn: "uyg-problem-kapat-olaylar",
            key: "uyg-problem-kapatma-aciklama",
            label: "Kapatılacak bağlantılı olayların kapatma açıklaması",
            type: "text",
          },
          { key: "uyg-problem-iliskili-durum-degisikligi", label: "İlişkili Problemin Durum Değişikliği", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          {
            // koşullu: uyg-problem-iliskili-durum-degisikligi
            key: "uyg-problem-baglantili-olay-durum",
            label: "Bağlantılı Olayların Durumunu Değiştir",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            // koşullu: uyg-problem-iliskili-durum-degisikligi
            key: "uyg-problem-cozum-olaya-kopyala",
            label: "Problem Çözümünü Bağlantılı Olaya Kopyalayın",
            type: "switch",
            defaultChecked: true,
          },
          { key: "uyg-problem-tekrar-acilirsa-olay-ac", label: "Problem tekrar açılırsa bağlantılı olayları aç", type: "switch", defaultChecked: true },
          { key: "uyg-ileri-olay-problem-yonetimi", label: "İleri Seviye Olay-Problem Yönetimi", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-entegrasyon",
        title: "Entegrasyon",
        layout: "stack",
        fields: [
          { key: "uyg-olay-entegrasyon-no", label: "Olay Entegrasyon Numarasını Görünür Yap", type: "switch", defaultChecked: true },
          { key: "uyg-istek-entegrasyon-no", label: "İstek Entegrasyon Numarasını Görünür Yap", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-beta",
        title: "Yeni Arayüz (Beta)",
        layout: "stack",
        fields: [
          { key: "uyg-beta-olay", label: "Yeni Olaylar sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-istek", label: "Yeni İstekler Özel Formuna yönlendir", type: "switch", defaultChecked: true },
          { key: "uyg-beta-problem", label: "Yeni problemler sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-istek-v2", label: "Yeni İstek V2 sayfasına yönlendir", type: "switch", defaultChecked: true },
          { key: "uyg-beta-cagri", label: "Yeni Çağrı sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-bilgi-bankasi", label: "Yeni bilgi bankası sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-duyuru", label: "Yeni duyuru sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-son-kullanici", label: "Yeni son kullanıcı sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-degisiklik", label: "Yeni değişiklik sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-iyilestirme", label: "Yeni iyileştirme sayfalarına yönlendir (beta)", type: "switch", defaultChecked: true },
          { key: "uyg-beta-gorev-is-gunlugu", label: "Görevler Sayfası Yeni İş Günlüğü Formu (beta)", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-form-validasyon",
        title: "Form Validasyonu",
        layout: "stack",
        fields: [
          { key: "uyg-olay-form-validasyon", label: "Olay Formu Validasyon Kontrolünü Kapat", type: "switch", defaultChecked: true },
          { key: "uyg-problem-form-validasyon", label: "Problem Formu Validasyon Kontrolünü Kapat", type: "switch", defaultChecked: true },
          { key: "uyg-istek-form-validasyon", label: "İstek Formu Validasyon Kontrolünü Kapat", type: "switch", defaultChecked: true },
          { key: "uyg-degisiklik-form-validasyon", label: "Değişiklik Formu Validasyon Kontrolünü Kapat", type: "switch", defaultChecked: true },
          { key: "uyg-iyilestirme-form-validasyon", label: "Sürekli İyileştirme Formu Validasyon Kontrolünü Kapat", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-alanlar-formlar",
        title: "Alanlar ve Formlar",
        layout: "stack",
        fields: [
          { key: "uyg-olay-detay-tab-gizle", label: "Olay Detay Tabları Gizle", type: "tags", placeholder: "Seçiniz", options: [] },
          { key: "uyg-hassas-veriler", label: "Hassas Veriler", type: "tags", placeholder: "Seçiniz", options: [] },
          { key: "uyg-olay-liste-ozel-alan", label: "Olaylar Listesine Özel Alanı Ekle", type: "multiselect", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-olay-baginti-problem-alan", label: "Olaylar Bağıntılarına Problem Özel Alan Ekle", type: "multiselect", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-ozel-form-katalog", label: "Özel Formun Açılacağı Katalog Öğeleri", type: "multiselect", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-genel-bakis-kolonlar", label: "Genel Bakış Gizlenecek Alanlar", type: "tags", placeholder: "Seçiniz", options: [] },
          { key: "uyg-paylasilacak-filtre-alan", label: "Paylaşılacak Kullanıcıların Filtrelenecek Alanı", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-ust-kategori-secimi", label: "Üst kategori seçimi", type: "switch", defaultChecked: true },
          { key: "uyg-react-liste-tab-iptal", label: "React Liste Sayfalarında Tab'ların Kaydedilmesini İptal Et", type: "multiselect", placeholder: "Seçiniz", searchable: true, options: [] },
        ],
      },
      {
        key: "uyg-gorev",
        title: "Görev",
        layout: "stack",
        fields: [
          { key: "uyg-gorev-gerceklesen-tarih-bagimli", label: "Görev kayıtlarında Gerçekleşen Tarih alanları Tarih alanlarına bağımlı çalışsın", type: "switch", defaultChecked: true },
          { key: "uyg-gorev-bitis-saat-ekle", label: "Görev kayıtlarında Bitiş Tarihine saat ekle", type: "switch", defaultChecked: true },
          { key: "uyg-gorev-is-gunlugu-teknisyen", label: "Yeni iş günlüğü eklerken giriş yapan teknisyen gelsin mi?", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-raporlama",
        title: "Raporlama",
        layout: "stack",
        fields: [
          { key: "uyg-dokum-rapor-kayit-sayisi", label: "Döküm Raporu için varsayılan parçalanan kayıt sayısı", type: "number", defaultValue: 900000, min: 0, wide: true },
        ],
      },
      {
        key: "uyg-degisiklik",
        title: "Değişiklik",
        layout: "stack",
        fields: [
          { key: "uyg-degisiklik-ozel-alan-istek-guncelle", label: "Değişiklik özel alanları güncellenince ilişkili istek kayıtlarındaki özel alanları da güncelle", type: "switch", defaultChecked: true },
          { key: "uyg-degisiklik-kapatinca-istek-kapat", label: "Değişiklik kaydı kapatıldığında ilişkili istek kayıtlarını da kapat", type: "switch", defaultChecked: true },
          {
            dependsOn: "uyg-degisiklik-kapatinca-istek-kapat",
            key: "uyg-degisiklik-istek-kapatma-esgec",
            label: "İlişkili istek kayıtlarını kapatırken kapatma kurallarını es geç",
            type: "switch",
            defaultChecked: true,
          },
          {
            dependsOn: "uyg-degisiklik-kapatinca-istek-kapat",
            key: "uyg-degisiklik-istek-durum",
            label: "Kapatılacak ilişkili isteklere atanacak durum",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            dependsOn: "uyg-degisiklik-kapatinca-istek-kapat",
            key: "uyg-degisiklik-istek-kapatma-gerekce",
            label: "Kapatılacak ilişkili isteklere atanacak kapatma gerekçesi",
            type: "select",
            placeholder: "Seçiniz",
            searchable: true,
            options: [],
          },
          {
            dependsOn: "uyg-degisiklik-kapatinca-istek-kapat",
            key: "uyg-degisiklik-istek-kapatma-aciklama",
            label: "Kapatılacak ilişkili isteklere atanacak kapatma açıklaması",
            type: "text",
          },
        ],
      },
      {
        key: "uyg-grafik",
        title: "Grafik",
        layout: "stack",
        fields: [
          { key: "uyg-grafik-rengi", label: "Grafik Rengi Seçiniz", type: "color" },
          { key: "uyg-grafik-karisik-palet", label: "Grafik gösterimlerinde karışık renk paleti kullanılsın mı?", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-katalog-servis",
        title: "Katalog ve Servis",
        layout: "stack",
        fields: [
          { key: "uyg-servis-kategori-kirilimli", label: "Servis Kategorisi Kırılımlı Gelsin Mi?", type: "switch", defaultChecked: true },
          { key: "uyg-servis-oge-kayit-sayisi-sirala", label: "Servis Ögeleri Açılan Kayıt Sayısına Göre Sıralansın mı?", type: "switch", defaultChecked: true },
          { key: "uyg-katalog-alt-kirilim-filtre", label: "Katalog Kategorilerini Alt Kırılımına Göre Filtrele.", type: "switch", defaultChecked: true },
        ],
      },
      {
        key: "uyg-bildirim",
        title: "Bildirim",
        layout: "stack",
        fields: [
          { key: "uyg-msteams-uye-bildirim", label: "Ms Teams grup bildirimlerinde üyelere de bildirim gönder", type: "switch", defaultChecked: true },
          { key: "uyg-gorusme-cevap-ilgili-kullanici", label: "Gönderilen Görüşme Cevaplamasında İlgili Kullanıcıyı Ekle", type: "switch", defaultChecked: true },
          { key: "uyg-bildirim-eposta-okuma-alani", label: "Kullanıcılara gidecek bildirimlerin kullanıcı tablosunun hangi alanından okunması gerektiğini belirtilen ayardır", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-sms-alici-alan", label: "Sms gönderiminde alıcı bilgisi için kullanılacak alan", type: "select", placeholder: "Seçiniz", searchable: true, options: [] },
        ],
      },
      {
        key: "uyg-oncelik-matrisi",
        title: "Öncelik Matrisi",
        layout: "stack",
        fields: [
          { key: "uyg-oncelik-matris-moduller", label: "Öncelik Matrisi Uygulanacak Modüller", type: "multiselect", placeholder: "Seçiniz", searchable: true, options: [] },
          { key: "uyg-oncelik-matris-esas", label: "Öncelik Belirlemede Matris Esas Alınsın", type: "switch", defaultChecked: true },
        ],
      },
    ],
  },
  {
    key: "guvenlik",
    label: "Güvenlik Ayarları",
    sections: [
      {
        key: "parola-ilkeleri",
        title: "Parola İlkeleri",
        layout: "stack",
        fields: [
          { key: "guv-buyuk-harf", label: "En Az 1 Adet Büyük Harf", type: "switch" },
          { key: "guv-kucuk-harf", label: "En Az 1 Adet Küçük Harf", type: "switch" },
          { key: "guv-sayisal", label: "En Az 1 Adet Sayısal Değer", type: "switch" },
          { key: "guv-sembol", label: "En Az 1 Adet Sembol Karakter", type: "switch" },
          { key: "guv-min-uzunluk", label: "Minimum Parola Uzunluğu", type: "number", min: 0 },
        ],
      },
    ],
  },
];
