import {
  Activity,
  AlertOctagon,
  ArrowLeftRight,
  Award,
  BarChart3,
  BellRing,
  BookCheck,
  BookOpen,
  Building,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Compass,
  Crown,
  Database,
  Download,
  FileSignature,
  FlaskConical,
  Gem,
  Globe,
  GraduationCap,
  Hammer,
  Inbox,
  Key,
  KeyRound,
  Layers,
  LayoutGrid,
  LifeBuoy,
  LineChart,
  ListChecks,
  ListTree,
  Mail,
  MailCheck,
  MessageCircle,
  Network,
  PackagePlus,
  Pencil,
  Phone,
  Plug,
  Power,
  Presentation,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings,
  Settings2,
  ShieldCheck,
  Sparkles,
  Star,
  Timer,
  UserCheck,
  UserCog,
  Users,
  Workflow,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const HIZMET_ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  AlertOctagon,
  ArrowLeftRight,
  Award,
  BarChart3,
  BellRing,
  BookCheck,
  BookOpen,
  Building,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Compass,
  Crown,
  Database,
  Download,
  FileSignature,
  FlaskConical,
  Gem,
  Globe,
  GraduationCap,
  Hammer,
  Inbox,
  Key,
  KeyRound,
  Layers,
  LayoutGrid,
  LifeBuoy,
  LineChart,
  ListChecks,
  ListTree,
  Mail,
  MailCheck,
  MessageCircle,
  Network,
  PackagePlus,
  Pencil,
  Phone,
  Plug,
  Power,
  Presentation,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings,
  Settings2,
  ShieldCheck,
  Sparkles,
  Star,
  Timer,
  UserCheck,
  UserCog,
  Users,
  Workflow,
  Wrench,
  XCircle,
  Zap,
};

export interface AccentTone {
  iconBg: string;
  iconBorder: string;
  iconText: string;
  badgeBg: string;
  badgeBorder: string;
  badgeText: string;
  cardHoverGradient: string;
  ctaText: string;
  ctaHover: string;
  gradientFrom: string;
  gradientTo: string;
  headerGradient: string;
  glowBg: string;
}

export const ACCENT_TONES: Record<string, AccentTone> = {
  blue: {
    iconBg: "bg-blue-500/15",
    iconBorder: "border-blue-500/25",
    iconText: "text-(--color-accent-blue-light)",
    badgeBg: "bg-blue-500/10",
    badgeBorder: "border-blue-500/20",
    badgeText: "text-(--color-accent-blue-light)",
    cardHoverGradient: "from-blue-500/10",
    ctaText: "text-(--color-accent-blue-light)",
    ctaHover: "hover:text-blue-300",
    gradientFrom: "from-blue-400",
    gradientTo: "to-cyan-400",
    headerGradient: "from-blue-400 to-cyan-400",
    glowBg: "bg-blue-600/20",
  },
  cyan: {
    iconBg: "bg-cyan-500/15",
    iconBorder: "border-cyan-500/25",
    iconText: "text-(--color-accent-cyan-light)",
    badgeBg: "bg-cyan-500/10",
    badgeBorder: "border-cyan-500/20",
    badgeText: "text-(--color-accent-cyan-light)",
    cardHoverGradient: "from-cyan-500/10",
    ctaText: "text-(--color-accent-cyan-light)",
    ctaHover: "hover:text-cyan-300",
    gradientFrom: "from-cyan-400",
    gradientTo: "to-blue-400",
    headerGradient: "from-cyan-400 to-blue-400",
    glowBg: "bg-cyan-500/20",
  },
  emerald: {
    iconBg: "bg-emerald-500/15",
    iconBorder: "border-emerald-500/25",
    iconText: "text-(--color-accent-emerald-light)",
    badgeBg: "bg-emerald-500/10",
    badgeBorder: "border-emerald-500/20",
    badgeText: "text-(--color-accent-emerald-light)",
    cardHoverGradient: "from-emerald-500/10",
    ctaText: "text-(--color-accent-emerald-light)",
    ctaHover: "hover:text-emerald-300",
    gradientFrom: "from-emerald-400",
    gradientTo: "to-cyan-400",
    headerGradient: "from-emerald-400 to-cyan-400",
    glowBg: "bg-emerald-500/20",
  },
  purple: {
    iconBg: "bg-purple-500/15",
    iconBorder: "border-purple-500/25",
    iconText: "text-(--color-accent-purple-light)",
    badgeBg: "bg-purple-500/10",
    badgeBorder: "border-purple-500/20",
    badgeText: "text-(--color-accent-purple-light)",
    cardHoverGradient: "from-purple-500/10",
    ctaText: "text-(--color-accent-purple-light)",
    ctaHover: "hover:text-purple-300",
    gradientFrom: "from-purple-400",
    gradientTo: "to-pink-400",
    headerGradient: "from-purple-400 to-pink-400",
    glowBg: "bg-purple-500/20",
  },
  amber: {
    iconBg: "bg-amber-500/15",
    iconBorder: "border-amber-500/25",
    iconText: "text-amber-300",
    badgeBg: "bg-amber-500/10",
    badgeBorder: "border-amber-500/20",
    badgeText: "text-amber-300",
    cardHoverGradient: "from-amber-500/10",
    ctaText: "text-amber-300",
    ctaHover: "hover:text-amber-200",
    gradientFrom: "from-amber-400",
    gradientTo: "to-red-400",
    headerGradient: "from-amber-400 to-red-400",
    glowBg: "bg-amber-500/20",
  },
  slate: {
    iconBg: "bg-slate-500/15",
    iconBorder: "border-slate-500/25",
    iconText: "text-slate-300",
    badgeBg: "bg-slate-500/10",
    badgeBorder: "border-slate-500/20",
    badgeText: "text-slate-300",
    cardHoverGradient: "from-slate-500/10",
    ctaText: "text-slate-300",
    ctaHover: "hover:text-slate-100",
    gradientFrom: "from-slate-300",
    gradientTo: "to-slate-500",
    headerGradient: "from-slate-300 to-slate-500",
    glowBg: "bg-slate-500/20",
  },
};

export function getAccentTone(accent: string): AccentTone {
  return ACCENT_TONES[accent] ?? ACCENT_TONES.blue;
}
